apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacityfinal-nodejs
  labels:
    app: udacityfinal-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacityfinal-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacityfinal-nodejs
    spec:
      containers:
      - image: amar2507/udacityfinal:19
        imagePullPolicy: Always
        name: udacityfinal-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP