apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitydemo-nodejs
  labels:
    app: udacitydemo-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacitydemo-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacitydemo-nodejs
    spec:
      containers:
      - image: amar2507/udacityfinal:latest
        imagePullPolicy: Always
        name: udacitydemo-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP